BEGIN;
SELECT plan(74);
SELECT todo('Two regexp need fix', 2);
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah'::url;$$,'http://foo.com/blah_blah');
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah/'::url;$$,'http://foo.com/blah_blah/');
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah_(wikipedia)'::url;$$,'http://foo.com/blah_blah_(wikipedia)');
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah_(wikipedia)_(again)'::url;$$,'http://foo.com/blah_blah_(wikipedia)_(again)');
SELECT lives_ok($$SELECT 'http://www.example.com/wpstyle/?p=364'::url;$$,'http://www.example.com/wpstyle/?p=364');
SELECT lives_ok($$SELECT 'https://www.example.com/foo/?bar=baz&inga=42&quux'::url;$$,'https://www.example.com/foo/?bar=baz&inga=42&quux');
SELECT lives_ok($$SELECT 'http://✪df.ws/123'::url;$$,'http://✪df.ws/123');
SELECT lives_ok($$SELECT 'http://userid:password@example.com:8080'::url;$$,'http://userid:password@example.com:8080');
SELECT lives_ok($$SELECT 'http://userid:password@example.com:8080/'::url;$$,'http://userid:password@example.com:8080/');
SELECT lives_ok($$SELECT 'http://userid@example.com'::url;$$,'http://userid@example.com');
SELECT lives_ok($$SELECT 'http://userid@example.com/'::url;$$,'http://userid@example.com/');
SELECT lives_ok($$SELECT 'http://userid@example.com:8080'::url;$$,'http://userid@example.com:8080');
SELECT lives_ok($$SELECT 'http://userid@example.com:8080/'::url;$$,'http://userid@example.com:8080/');
SELECT lives_ok($$SELECT 'http://userid:password@example.com'::url;$$,'http://userid:password@example.com');
SELECT lives_ok($$SELECT 'http://userid:password@example.com/'::url;$$,'http://userid:password@example.com/');
SELECT lives_ok($$SELECT 'http://142.42.1.1/'::url;$$,'http://142.42.1.1/');
SELECT lives_ok($$SELECT 'http://142.42.1.1:8080/'::url;$$,'http://142.42.1.1:8080/');
SELECT lives_ok($$SELECT 'http://➡.ws/䨹'::url;$$,'http://➡.ws/䨹');
SELECT lives_ok($$SELECT 'http://⌘.ws'::url;$$,'http://⌘.ws');
SELECT lives_ok($$SELECT 'http://⌘.ws/'::url;$$,'http://⌘.ws/');
SELECT lives_ok($$SELECT 'http://foo.com/blah_(wikipedia)#cite-1'::url;$$,'http://foo.com/blah_(wikipedia)#cite-1');
SELECT lives_ok($$SELECT 'http://foo.com/blah_(wikipedia)_blah#cite-1'::url;$$,'http://foo.com/blah_(wikipedia)_blah#cite-1');
SELECT lives_ok($$SELECT 'http://foo.com/unicode_(✪)_in_parens'::url;$$,'http://foo.com/unicode_(✪)_in_parens');
SELECT lives_ok($$SELECT 'http://foo.com/(something)?after=parens'::url;$$,'http://foo.com/(something)?after=parens');
SELECT lives_ok($$SELECT 'http://☺.damowmow.com/'::url;$$,'http://☺.damowmow.com/');
SELECT lives_ok($$SELECT 'http://code.google.com/events/#&product=browser'::url;$$,'http://code.google.com/events/#&product=browser');
SELECT lives_ok($$SELECT 'http://j.mp'::url;$$,'http://j.mp');
SELECT lives_ok($$SELECT 'ftp://foo.bar/baz'::url;$$,'ftp://foo.bar/baz');
SELECT lives_ok($$SELECT 'http://foo.bar/?q=Test%20URL-encoded%20stuff'::url;$$,'http://foo.bar/?q=Test%20URL-encoded%20stuff');
SELECT lives_ok($$SELECT 'http://مثال.إختبار'::url;$$,'http://مثال.إختبار');
SELECT lives_ok($$SELECT 'http://例子.测试'::url;$$,'http://例子.测试');
SELECT lives_ok($$SELECT 'http://उदाहरण.परीक्षा'::url;$$,'http://उदाहरण.परीक्षा');
SELECT lives_ok($$SELECT 'http://-.~_!$&''()*+,;=:%40:80%2f::::::@example.com'::url;$$,'http://-.~_!$&''()*+,;=:%40:80%2f::::::@example.com');
SELECT lives_ok($$SELECT 'http://1337.net'::url;$$,'http://1337.net');
SELECT lives_ok($$SELECT 'http://a.b-c.de'::url;$$,'http://a.b-c.de');
SELECT lives_ok($$SELECT 'http://223.255.255.254'::url;$$,'http://223.255.255.254');
SELECT throws_ok($$SELECT 'http://'::url;$$,23514,NULL,'http://');
SELECT throws_ok($$SELECT 'http://.'::url;$$,23514,NULL,'http://.');
SELECT throws_ok($$SELECT 'http://..'::url;$$,23514,NULL,'http://..');
SELECT throws_ok($$SELECT 'http://../'::url;$$,23514,NULL,'http://../');
SELECT throws_ok($$SELECT 'http://?'::url;$$,23514,NULL,'http://?');
SELECT throws_ok($$SELECT 'http://??'::url;$$,23514,NULL,'http://??');
SELECT throws_ok($$SELECT 'http://??/'::url;$$,23514,NULL,'http://??/');
SELECT throws_ok($$SELECT 'http://#'::url;$$,23514,NULL,'http://#');
SELECT throws_ok($$SELECT 'http://##'::url;$$,23514,NULL,'http://##');
SELECT throws_ok($$SELECT 'http://##/'::url;$$,23514,NULL,'http://##/');
SELECT throws_ok($$SELECT 'http://foo.bar?q=Spaces should be encoded'::url;$$,23514,NULL,'http://foo.bar?q=Spaces should be encoded');
SELECT throws_ok($$SELECT '//'::url;$$,23514,NULL,'//');
SELECT throws_ok($$SELECT '//a'::url;$$,23514,NULL,'//a');
SELECT throws_ok($$SELECT '///a'::url;$$,23514,NULL,'///a');
SELECT throws_ok($$SELECT '///'::url;$$,23514,NULL,'///');
SELECT throws_ok($$SELECT 'http:///a'::url;$$,23514,NULL,'http:///a');
SELECT throws_ok($$SELECT 'foo.com'::url;$$,23514,NULL,'foo.com');
SELECT throws_ok($$SELECT 'rdar://1234'::url;$$,23514,NULL,'rdar://1234');
SELECT throws_ok($$SELECT 'h://test'::url;$$,23514,NULL,'h://test');
SELECT throws_ok($$SELECT 'http:// shouldfail.com'::url;$$,23514,NULL,'http:// shouldfail.com');
SELECT throws_ok($$SELECT ':// should fail'::url;$$,23514,NULL,':// should fail');
SELECT throws_ok($$SELECT 'http://foo.bar/foo(bar)baz quux'::url;$$,23514,NULL,'http://foo.bar/foo(bar)baz quux');
SELECT throws_ok($$SELECT 'ftps://foo.bar/'::url;$$,23514,NULL,'ftps://foo.bar/');
SELECT throws_ok($$SELECT 'http://-error-.invalid/'::url;$$,23514,NULL,'http://-error-.invalid/');
SELECT todo_start( 'Should fail' );
SELECT throws_ok($$SELECT 'http://a.b--c.de/'::url;$$,23514,NULL,'http://a.b--c.de/');
SELECT todo_end();
SELECT throws_ok($$SELECT 'http://-a.b.co'::url;$$,23514,NULL,'http://-a.b.co');
SELECT throws_ok($$SELECT 'http://a.b-.co'::url;$$,23514,NULL,'http://a.b-.co');
SELECT throws_ok($$SELECT 'http://0.0.0.0'::url;$$,23514,NULL,'http://0.0.0.0');
SELECT throws_ok($$SELECT 'http://10.1.1.0'::url;$$,23514,NULL,'http://10.1.1.0');
SELECT throws_ok($$SELECT 'http://10.1.1.255'::url;$$,23514,NULL,'http://10.1.1.255');
SELECT throws_ok($$SELECT 'http://224.1.1.1'::url;$$,23514,NULL,'http://224.1.1.1');
SELECT throws_ok($$SELECT 'http://1.1.1.1.1'::url;$$,23514,NULL,'http://1.1.1.1.1');
SELECT throws_ok($$SELECT 'http://123.123.123'::url;$$,23514,NULL,'http://123.123.123');
SELECT throws_ok($$SELECT 'http://3628126748'::url;$$,23514,NULL,'http://3628126748');
SELECT throws_ok($$SELECT 'http://.www.foo.bar/'::url;$$,23514,NULL,'http://.www.foo.bar/');
SELECT todo_start( 'Should fail' );
SELECT throws_ok($$SELECT 'http://www.foo.bar./'::url;$$,23514,NULL,'http://www.foo.bar./');
SELECT todo_end();
SELECT throws_ok($$SELECT 'http://.www.foo.bar./'::url;$$,23514,NULL,'http://.www.foo.bar./');
SELECT throws_ok($$SELECT 'http://10.1.1.1'::url;$$,23514,NULL,'http://10.1.1.1');
SELECT * FROM finish();
ROLLBACK;
